app:
    resource: "@AppBundle/Controller/"
    type:     annotation

rest_article:
    type: rest
    prefix: /api/v1
    resource: "@IronwebBundle/Controller/"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
