app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

rest:
    type: rest
    prefix: /api/v1
    resource: "@IronwebBundle/Resources/config/routing.yml"
